const words = ['modern', 'world', 'current', 'prevailing', 'funtime', 'automation', 'software', 'applied', 'rapid', 'new', 'dynamics', 'automated', 'productivity', 'meritus', 'quality', 'dynamic', 'signal', 'designs', 'command', 'concrete', 'elements', 'composition', 'structure', 'tactics', 'systems', 'company', 'service', 'nuclear', 'features', 'world', 'technology', 'classic', 'laser', 'software', 'applying', '90', '78', 'coding', 'exclusive', 'velocity', 'strategy', 'object', 'abstract', 'types', 'evolving', 'smart', 'unison', 'programs', 'applications', 'times', 'products', 'simple', 'tactical', 'results','art', 'functions', 'art', 'sights', 'patterns', 'support', 'inheiritance', 'distinct', 'component', 'flexible', 'programmable', 'information', 'programming', 'boolean', 'semicolon', 'functional', 'library', 'multiple', 'rewritten', 'deploy', 'streams', 'input', 'object-oriented', 'proxies', 'proxy', 'inner classes','exception', 'concurrency','event listener', 'graphical', 'compiling', 'console', 'editor', 'loops', 'methods', 'classes', 'concepts', 'story', 'objects', 'fundamental', 'technique', 'mechanism', 'interface', 'mastering', 'force', 'recon', 'mission', 'specops', 'raptor', 'master', 'global', 'defensive', 'csar', 'basic', 'integrated', 'comms', 'range', 'gear', 'survival', 'intelligent', 'advanced', 'pro', 'op', 'raider', 'fighting', 'forges','soldier', 'cqb', 'ops', 'universal', 'unikit', 'uni', 'kit', 'dangerclose', 'green', 'warfare', 'camo', 'elite', 'dod', 'mounts', 'platform', 'dominance', 'initiative', 'military', 'battle kit', 'core', 'fight','fighter', 'combat', 'urban', 'duty', 'utility', 'group', 'special', 'force', 'direct', 'response', 'extreme', 'products', 'lite', 'system', 'equipment', 'united', 'battle', 'security', 'aid', 'pro', 'counter', 'strike', 'xtreme', 'operator', 'essential', 'core', 'life', 'total'];

document.getElementById('generate').addEventListener('click', generateWords);

function generateWords() {
    var wordsLength = words.length - 1;
    var randomFirstWord = Math.floor(Math.random() * wordsLength);
    var randomSecondWord = Math.floor(Math.random() * wordsLength);
    var word = document.getElementById('word').innerHTML = words[randomFirstWord] + ' ' + words[randomSecondWord];
    return word;
} 